go to website https://the-internet.herokuapp.com
click on A/B Testing
save screenshot as "the-internet.herokuapp.com_1.png"
go to website https://the-internet.herokuapp.com
click on Add/Remove Elements
save screenshot as "the-internet.herokuapp.com_3.png"
